# Generated by Django 5.2.17 on 2026-08-19 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0002_company_industry_company_size"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="about",
            field=models.TextField(
                blank=True, help_text="Extended company about section"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="benefits",
            field=models.JSONField(
                blank=True, default=list, help_text="List of benefits/perks"
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="cover_photo",
            field=models.ImageField(blank=True, null=True, upload_to="company_covers/"),
        ),
        migrations.AddField(
            model_name="company",
            name="culture",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="company",
            name="followers_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="company",
            name="founded_year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="mission",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="company",
            name="specialities",
            field=models.JSONField(
                blank=True, default=list, help_text="List of specialities"
            ),
        ),
        migrations.CreateModel(
            name="CompanyReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")]
                    ),
                ),
                ("pros", models.TextField(blank=True)),
                ("cons", models.TextField(blank=True)),
                (
                    "employment_status",
                    models.CharField(
                        choices=[
                            ("current", "Current Employee"),
                            ("former", "Former Employee"),
                        ],
                        default="current",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="recruiters.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CompanyFollower",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to="recruiters.company",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_follows",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("user", "company")},
            },
        ),
    ]
