# Generated by Django 5.2.15 on 2026-07-24 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0003_job_category_job_preferred_skills_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("description", models.TextField()),
                ("icon", models.CharField(default="fa-code", max_length=50)),
                ("color", models.CharField(default="#2563eb", max_length=20)),
                (
                    "avg_salary_min",
                    models.IntegerField(
                        default=0, help_text="Minimum average salary in USD"
                    ),
                ),
                (
                    "avg_salary_max",
                    models.IntegerField(
                        default=0, help_text="Maximum average salary in USD"
                    ),
                ),
                (
                    "growth_outlook",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'Growing 22% annually'",
                        max_length=100,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CareerPathMilestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("entry", "Entry Level"),
                            ("mid", "Mid Level"),
                            ("senior", "Senior"),
                            ("lead", "Lead / Manager"),
                            ("principal", "Principal / Architect"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("order", models.IntegerField(default=0)),
                (
                    "experience_years",
                    models.CharField(default="0-2 years", max_length=50),
                ),
                ("salary_range", models.CharField(blank=True, max_length=100)),
                (
                    "career_path",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="careers.careerpath",
                    ),
                ),
                (
                    "skills_required",
                    models.ManyToManyField(
                        blank=True, related_name="milestones", to="jobs.skill"
                    ),
                ),
            ],
            options={
                "ordering": ["career_path", "order"],
            },
        ),
        migrations.CreateModel(
            name="InterviewQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField()),
                (
                    "answer",
                    models.TextField(
                        blank=True, help_text="Model answer for reference"
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                (
                    "is_behavioral",
                    models.BooleanField(
                        default=False, help_text="Is this a behavioral question?"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "career_path",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="questions",
                        to="careers.careerpath",
                    ),
                ),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interview_questions",
                        to="jobs.skill",
                    ),
                ),
            ],
            options={
                "ordering": ["skill", "difficulty"],
            },
        ),
        migrations.CreateModel(
            name="SkillResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("url", models.URLField()),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("course", "Online Course"),
                            ("tutorial", "Tutorial"),
                            ("article", "Article"),
                            ("video", "Video"),
                            ("book", "Book"),
                            ("documentation", "Documentation"),
                        ],
                        default="tutorial",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="beginner",
                        max_length=20,
                    ),
                ),
                ("is_free", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "skill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_resources",
                        to="jobs.skill",
                    ),
                ),
            ],
            options={
                "ordering": ["skill", "difficulty"],
            },
        ),
    ]
