# Generated by Django 5.2.17 on 2026-08-19 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0003_job_category_job_preferred_skills_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="applicants_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="job",
            name="easy_apply",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="JobAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Custom name for this alert",
                        max_length=200,
                    ),
                ),
                (
                    "keywords",
                    models.CharField(
                        blank=True, help_text="Search keywords", max_length=300
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=255)),
                ("job_type", models.CharField(blank=True, max_length=50)),
                ("min_salary", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("instant", "Instant"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_sent", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="jobs.category",
                    ),
                ),
                ("skills", models.ManyToManyField(blank=True, to="jobs.skill")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
