# Generated by Django 5.2.14 on 2026-05-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="github_username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="studentprofile",
            name="verified_github_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
