# Generated by Django 5.2.15 on 2026-08-09 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_studentprofile_github_username_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentprofile",
            name="projects",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
