# Generated by Django 5.2.17 on 2026-08-26 11:04

import portal.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_studentprofile_projects"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentprofile",
            name="resume",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="resumes/",
                validators=[portal.validators.ResumeFileValidator()],
            ),
        ),
    ]
