# Generated by Django 5.2.14 on 2026-05-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recruiters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="industry",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="company",
            name="size",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
