# Generated by Django 5.2.14 on 2026-06-02 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
        (
            "internships",
            "0002_internship_category_internship_preferred_skills_and_more",
        ),
        ("jobs", "0003_job_category_job_preferred_skills_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="internship",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="internships.internship",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="jobs.job",
            ),
        ),
    ]
