# Generated by Django 5.2.17 on 2026-08-26 11:04

import portal.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_application_internship_alter_application_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="resume",
            field=models.FileField(
                upload_to="application_resumes/",
                validators=[portal.validators.ResumeFileValidator()],
            ),
        ),
    ]
