# Generated by Django 5.2.14 on 2026-05-28 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_savedjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="jobs.category",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="preferred_skills",
            field=models.ManyToManyField(
                blank=True, related_name="preferred_jobs", to="jobs.skill"
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="skills_required",
            field=models.ManyToManyField(
                related_name="mandatory_jobs", to="jobs.skill"
            ),
        ),
    ]
